[package]
name = "compressed_log"
version = "0.1.1"
authors = ["Michał Papierski <michal@papierski.net>"]
edition = "2018"
include = [
    "**/*.rs",
    "Cargo.toml"
]
description = "Log compression on the fly"
repository = "https://github.com/mpapierski/compressed_log"
license-file = "LICENSE"

[dependencies]
lz4 = "1.23"
log = { version = "0.4", features = ["std"] }
chrono = "0.4"
failure = "0.1"
actix = "0.7"
actix-web = { version = "0.7", features = ["ssl"] }
futures = "0.1"
backoff = "0.1"
