[package]
name = "compressed_log"
version = "0.1.0"
authors = ["Michał Papierski <michal@papierski.net>"]
edition = "2018"

[dependencies]
lz4 = "1.23.1"
log = { version = "0.4.6", features = ["std"] }
chrono = "0.4.6"
failure = "0.1.3"
actix = "0.7.9"
actix-web = "0.7.16"
futures = "0.1.25"